# Quinta Aula - Atividade Prática

#### Valor: 10 pontos

1) Solicite ao usuário que informe a quantidade de linhas (n) e colunas (m) e crie um ndarray nxm com valores aleatórios.

In [63]:
import numpy as np
                                               
N = int(input('Quantidade de linhas: '))                                                                 
                                                                                                                                                             
M = int(input('Quantidade de colunas: '))                                                             
                                                                                                                                                     
matrixA = [[int(input("valor: ")) for column in range(M)] for row in range(N)]

matrix = np.array(matrixA)

np.random.shuffle(matrix)

matrix

Quantidade de linhas: 3
Quantidade de colunas: 3
valor: 2
valor: 1
valor: 3
valor: 5
valor: 4
valor: 6
valor: 8
valor: 7
valor: 9


array([[5, 4, 6],
       [8, 7, 9],
       [2, 1, 3]])

2) Retorne a média dos valores de cada uma das n linhas

In [61]:
i = 0
total_sum = 0
soma_linha = 0
i = len(matrix)
j = 0
while j < i:
  for N in range(len(matrix)):
    soma_linha += matrix[j][N]
    print(matrix[j][N])
  total_sum += soma_linha
  soma_geral = total_sum / len(matrix[N])
  print('Soma: {} Média: {}'.format(total_sum, soma_geral))
  j+=1
  total_sum = 0
  soma_linha = 0

4
6
8
Soma: 18 Média: 6.0
3
1
2
Soma: 6 Média: 2.0
9
7
5
Soma: 21 Média: 7.0


3) Retorne a mediana dos valores das m colunas

In [87]:
import statistics
j = 0
n = []
while j < i:
  for N in range(len(matrix)):
    n.append(matrix[j][N])
  y = statistics.median(n)
  print(y)
  j+=1
  n=[]

5
8
2


4)  Dados os seguintes arrays x e y, calcula a correlação entre eles.

In [ ]:
import numpy as np
x = np.array([0, 1, 3, 8, -3])
y = np.array([5, 4, 2, 1, 7])
z = np.array([-5, -41, -97])

In [ ]:
dados = np.matrix([[0, 1, 3, 8, -3],
[5, 4, 2, 1, 7]])

print(np.corrcoef(dados))


[[ 1.         -0.95320714]
 [-0.95320714  1.        ]]


5) Faça uma função que receba um ndarray de valores inteiros e retorne um ndarray de mesma dimensão, onde os valores negativos serão substituídos por True e os valores positivos por False.

In [ ]:
def torf(ndarray):
  x = ndarray
  y = 0 >= x
  return y

In [ ]:
ndarray = []
lista = list()

for i in range(1,6):
  n = int(input("Escolha o {}º número: ".format(int(i))))
  lista.append(n)
ndarray = numpy.array([lista])
torf(ndarray)

Escolha o 1º número: -1
Escolha o 2º número: 2
Escolha o 3º número: -2
Escolha o 4º número: 3
Escolha o 5º número: 5


array([[ True, False,  True, False, False]])