In [ ]:
!pip install googletrans
!pip install googletrans==3.1.0a0
!pip install deep-translator

# Quinta Aula - Atividade Prática

#### Valor: 10 pontos

1) Solicite ao usuário que informe a quantidade de linhas (n) e colunas (m) e crie um ndarray nxm com valores aleatórios.

In [ ]:
import numpy as np
                                               
N = int(input('Quantidade de linhas: '))                                                                 
                                                                                                                                                             
M = int(input('Quantidade de colunas: '))                                                             
                                                                                                                                                     
matrixA = [[int(input("valor: ")) for column in range(M)] for row in range(N)]

matrix = np.array(matrixA)

np.random.shuffle(matrix)

matrix

Quantidade de linhas: 3
Quantidade de colunas: 3
valor: 2
valor: 1
valor: 3
valor: 5
valor: 4
valor: 6
valor: 8
valor: 7
valor: 9


array([[5, 4, 6],
       [8, 7, 9],
       [2, 1, 3]])

2) Retorne a média dos valores de cada uma das n linhas

In [ ]:
i = 0
total_sum = 0
soma_linha = 0
i = len(matrix)
j = 0
while j < i:
  for N in range(len(matrix)):
    soma_linha += matrix[j][N]
    print(matrix[j][N])
  total_sum += soma_linha
  soma_geral = total_sum / len(matrix[N])
  print('Soma: {} Média: {}'.format(total_sum, soma_geral))
  j+=1
  total_sum = 0
  soma_linha = 0

4
6
8
Soma: 18 Média: 6.0
3
1
2
Soma: 6 Média: 2.0
9
7
5
Soma: 21 Média: 7.0


3) Retorne a mediana dos valores das m colunas

In [ ]:
import statistics
j = 0
n = []
while j < i:
  for N in range(len(matrix)):
    n.append(matrix[j][N])
  y = statistics.median(n)
  print(y)
  j+=1
  n=[]

5
8
2


4)  Dados os seguintes arrays x e y, calcula a correlação entre eles.

In [ ]:
import numpy as np
x = np.array([0, 1, 3, 8, -3])
y = np.array([5, 4, 2, 1, 7])
z = np.array([-5, -41, -97])

In [ ]:
dados = np.matrix([[0, 1, 3, 8, -3],
[5, 4, 2, 1, 7]])

print(np.corrcoef(dados))


[[ 1.         -0.95320714]
 [-0.95320714  1.        ]]


5) Faça uma função que receba um ndarray de valores inteiros e retorne um ndarray de mesma dimensão, onde os valores negativos serão substituídos por True e os valores positivos por False.

In [ ]:
def torf(ndarray):
  x = ndarray
  y = 0 >= x
  return y

In [ ]:
ndarray = []
lista = list()

for i in range(1,6):
  n = int(input("Escolha o {}º número: ".format(int(i))))
  lista.append(n)
ndarray = numpy.array([lista])
torf(ndarray)

Escolha o 1º número: -1
Escolha o 2º número: 2
Escolha o 3º número: -2
Escolha o 4º número: 3
Escolha o 5º número: 5


array([[ True, False,  True, False, False]])

# Sexta Aula - Atividade Prática

#### Valor: 10 pontos

1) Importe a base de dados sobre carros no link: https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv

In [164]:
import pandas as pd

In [ ]:
dfcarros = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv" , sep=",", comment="#")
dfcarros

2) Renomeie os nomes das colunas do DataFrame para português

In [ ]:
from googletrans import Translator
translator = Translator()

def tradd(texttra):
  trad = translator.translate(texttra, src='auto', dest='pt')
  return trad.text
trans={}
for coluna in dfcarros.columns:
  trans[coluna] = tradd(coluna)
dfcarros.rename(columns=trans,inplace=True)
dfcarros

3) Substitua os valores faltantes (missings) das colunas Min. Price e Max. Price, com suas respectivas médias.

In [189]:
dfcarros.fillna(dfcarros[:3].mean(), inplace=True)
dfcarros.fillna(dfcarros[:4].mean(), inplace=True)

In [190]:
dfcarros["Min.Price"].isnull().sum()
dfcarros["Max.Price"].isnull().sum()

0

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None
dfcarros

4) Recupere a coluna Montadora (Manufacturer) como DataFrame, não como Series

In [ ]:
dfmontadora = dfcarros.loc[:, ["Manufacturer"]]
dfmontadora

5) Faça uma análise descritiva da base de dados

In [ ]:
dfcarros.describe()

6) Salve uma amostra da base com apenas 100 registros

In [195]:
dfamostra = dfcarros.head(10)
dfamostra.to_csv("amostra.csv")

In [196]:
pd.read_csv("amostra.csv")

Unnamed: 0 Manufacturer       Model     Type  Min.Price  Price  Max.Price  \
0           0        Acura     Integra    Small  12.900000   15.9  18.800000   
1           1          NaN      Legend  Midsize  29.200000   33.9  38.700000   
2           2         Audi          90  Compact  25.900000   29.1  32.300000   
3           3         Audi         100  Midsize  22.666667   37.7  44.600000   
4           4          BMW        535i  Midsize  22.666667   30.0  29.933333   
5           5        Buick     Century  Midsize  14.200000   15.7  17.300000   
6           6        Buick     LeSabre    Large  19.900000   20.8  29.933333   
7           7        Buick  Roadmaster    Large  22.600000   23.7  24.900000   
8           8        Buick     Riviera  Midsize  26.300000   26.3  26.300000   
9           9     Cadillac     DeVille    Large  33.000000   34.7  36.300000   

   MPG.city  MPG.highway             AirBags DriveTrain  Cylinders  \
0      25.0         31.0                None      Front          4   
1      18.0         25.0  Driver & Passenger      Front          6   
2      20.0         26.0         Driver only      Front          6   
3      19.0         26.0  Driver & Passenger        NaN          6   
4      22.0         30.0                 NaN       Rear          4   
5      22.0         31.0         Driver only        NaN          4   
6      19.0         28.0         Driver only      Front          6   
7      16.0         25.0         Driver only       Rear          6   
8      19.0         27.0         Driver only      Front          6   
9      16.0         25.0         Driver only      Front          8   

   EngineSize  Horsepower     RPM  Rev.per.mile Man.trans.avail  \
0         1.8       140.0  6300.0   2890.000000             Yes   
1         3.2       200.0  5500.0   2335.000000             Yes   
2         2.8       172.0  5500.0   2280.000000             Yes   
3         2.6       172.0  5500.0   2535.000000             NaN   
4         3.5       208.0  5700.0   2545.000000             Yes   
5         2.2       110.0  5200.0   2565.000000              No   
6         3.8       170.0  4800.0   2501.666667              No   
7         5.7       180.0  4000.0   1320.000000              No   
8         3.8       170.0  4800.0   1690.000000              No   
9         4.9       200.0  4100.0   2501.666667              No   

   Fuel.tank.capacity  Passengers  Length  Wheelbase      Width  Turn.circle  \
0           13.200000         5.0   177.0      102.0  68.000000         37.0   
1           18.000000         5.0   195.0      115.0  71.000000         38.0   
2           16.900000         5.0   180.0      102.0  67.000000         37.0   
3           21.100000         6.0   193.0      106.0  68.666667         37.0   
4           21.100000         4.0   186.0      109.0  69.000000         39.0   
5           16.400000         6.0   189.0      105.0  69.000000         41.0   
6           16.033333         6.0   200.0      111.0  74.000000         42.0   
7           23.000000         6.0   216.0      116.0  78.000000         45.0   
8           18.800000         5.0   198.0      108.0  68.666667         41.0   
9           18.000000         6.0   206.0      114.0  73.000000         43.0   

   Rear.seat.room  Luggage.room       Weight   Origin              Make  
0            26.5          14.5  2705.000000  non-USA     Acura Integra  
1            30.0          15.0  3560.000000  non-USA      Acura Legend  
2            28.0          14.0  3375.000000  non-USA           Audi 90  
3            31.0          17.0  3405.000000  non-USA          Audi 100  
4            27.0          13.0  3640.000000  non-USA          BMW 535i  
5            28.0          16.0  3213.333333      USA     Buick Century  
6            30.5          17.0  3470.000000      USA     Buick LeSabre  
7            30.5          21.0  4105.000000      USA  Buick Roadmaster  
8            26.5          14.0  3495.000000      USA     Buick Ri